spring.application.name=gymtrack
spring.datasource.url=jdbc:postgresql://localhost:5432/gymtrack
spring.datasource.username=brais
spring.datasource.password=#L0p3z2k25

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
