spring.application.name=gymtrack
spring.datasource.url=jdbc:postgresql://localhost:5432/gymtrack
spring.datasource.username=brais
spring.datasource.password=#L0p3z2k25

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

jwt.secret=ES_un_Secreto_De-TUUU-MIRADA.Y_LA_M1A,UNPR€SENT1M¡3NT0000...A
jwt.expiration=36000000
